#!/bin/bash -x

declare -A Birthday

Birthday[January]="A1"
Birthday[February]="A2"
Birthday[March]="A3"
Birthday[April]="A4"
Birthday[May]="A5"
Birthday[June]="A6"
Birthday[July]="A7"
Birthday[August]="A8"
Birthday[September]="A9"
Birthday[October]="A10"
Birthday[November]="A11"
Birthday[December]="A12"
Birthday[January]="A13"
Birthday[February]="A14"
Birthday[March]="A15"
Birthday[April]="A16"
Birthday[May]="A17"
Birthday[June]="A18"
Birthday[July]="A19"
Birthday[August]="A20"
Birthday[September]="A21"
Birthday[October]="A22"
Birthday[November]="A23"
Birthday[December]="A24"
Birthday[January]="A25"
Birthday[February]="A26"
Birthday[March]="A27"
Birthday[April]="A28"
Birthday[May]="A29"
Birthday[June]="A30"
Birthday[July]="A31"
Birthday[August]="A32"
Birthday[September]="A33"
Birthday[October]="A34"
Birthday[November]="A35"
Birthday[December]="A36"
Birthday[January]="A37"
Birthday[February]="A38"
Birthday[March]="A39"
Birthday[April]="A40"
Birthday[May]="A41"
Birthday[June]="A42"
Birthday[July]="A43"
Birthday[August]="A44"
Birthday[September]="A45"
Birthday[October]="A46"
Birthday[November]="A47"
Birthday[December]="A48"
Birthday[January]="A49"
Birthday[February]="A50"

echo "Birthday Month " ${Birthday[May]}
echo "Birthday Month " ${!Birthday[May]}
